# Generated by Django 4.0.1 on 2022-01-19 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shortener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='PurgeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('marked', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='urlshortener.shortener')),
            ],
        ),
    ]
